### ISSUE TITLE
Prepare new test images for image metadata enhencement

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/enclave-cc#108]
We are working on unifying the encrypted images on Attestation-Agent and image-rs side, related proposals are published (https://github.com/confidential-containers/attestation-agent/issues/113 and https://github.com/confidential-containers/documentation/issues/85). If interested please give any comments :-) The influence on enclave-cc are
- When we use new version of Attestation-Agent for CI, new images should be made or enclave-agent will fail to decrypt the old ones
- Wherever a confidential resource is used should be indicated in a [kbs uri format](https://github.com/Xynnn007/attestation-agent/blob/feat-uri/docs/KBS_URI.md)

I'd like to help with this when things of AA and image-rs are finished.

**Comment by Xynnn007** [comment]
Hi, there is a problem for enclave-cc. Now the [test CI under reviewing](https://github.com/confidential-containers/enclave-cc/pull/97) uses eaa-kbc for confidential resource brokering (both image decryption keys and policy/signature verification key,.etc ). However currently verdictd does not support the same addressing mode as kbs uri. So there might be two options for us:

- Use a fixed version of Attestation-Agent and Verdictd in CI and a fixed rev of `image-rs`. When SGX verifier support is ready in Attestation Service, we can migrate from eaa-verdictd to CC-KBC, CC-KBS and update the image-rs version. The reason for this is that new image-rs(developing) and AA(reviewing) will use KBS URI to index resources, and currently confidential resource brokering is not a key problem enclave-cc faces. 
- Refactor Verdictd to fit in KBS URI scheme. This can let the AA and image-rs version up-to-date. However this will take much effort to refactor verdictd, and @huliucheng1 has made great effort for current CI.

I prefer option 1, although there will be a time before AS supports SGX verification during which we should use `v0.3.0` AA and image-rs.

cc @hairongchen @mythi @haosanzi

**Comment by mythi** [comment]
@Xynnn007 thanks for the heads-up and sorry for the late reply (it was triggered by @fidencio's PR :-)

I haven't followed the latest attestation-agent/image-rs changes. #110 triggers a test failure with an image I had encrypted using `sample-kbs` long time ago. Is this related to what you're describing above or something different?

#97 I'm not yet too worried about because it's still WIP and needs a lot of rework still.

**Comment by Xynnn007** [comment]
> I haven't followed the latest attestation-agent/image-rs changes. #110 triggers a test failure with an image I had encrypted using `sample-kbs` long time ago. Is this related to what you're describing above or something different?

Yes, that is part of the things I've mentioned. We now have a unified format of [AnnotationPacket](https://github.com/confidential-containers/attestation-agent/blob/main/docs/IMAGE_ENCRYPTION.md#annotation-packet) in encrypted images in attestation-agent. The effection is all the images to be decrypted using eaa-kbc and sample-kbc will not pass.

A temporary solution is to still use the old version of image-rs (who imports attestation-agent as a dependency). And in future   we can remake new test images with the new key provider which is still under development

**Comment by mythi** [comment]
Thanks for the quick reply! Is the breaking change introduced by https://github.com/confidential-containers/image-rs/commit/cf2d6d00e431bf0e037b850c58267d51fd3655e1?

**Comment by Xynnn007** [comment]
> Thanks for the quick reply! Is the breaking change introduced by [confidential-containers/image-rs@cf2d6d0](https://github.com/confidential-containers/image-rs/commit/cf2d6d00e431bf0e037b850c58267d51fd3655e1)?

Yes

**Comment by Xynnn007** [comment]
cc @fidencio

**Comment by mythi** [comment]
> > Thanks for the quick reply! Is the breaking change introduced by [confidential-containers/image-rs@cf2d6d0](https://github.com/confidential-containers/image-rs/commit/cf2d6d00e431bf0e037b850c58267d51fd3655e1)?
> 
> Yes

Thanks. We will want to to update `image-rs` to a point without the breakages to get the dependency/perfomance updates. We just need to agree what sha the `v0.4.0` will point to.
