### ISSUE TITLE
update boot-instance Occlum to 0.29.7

### ISSUE THREAD

**Issue by mythi** [confidential-containers/enclave-cc#126]
agent-enclave uses 0.29.5 so it's good for this to follow:
https://github.com/confidential-containers/enclave-cc/blob/8164a4cf17c0f9ec7b82b3b61bd55b3607072e99/tools/packaging/build/boot-instance-bundle/Dockerfile#L24-L26

- [x] Change `image-rs` to use [`sefs` fstype instead of `unionfs`](https://github.com/confidential-containers/image-rs/blob/62288ee4cd275c3c9d02c7f650d2cad8d8920b04/src/snapshots/occlum/unionfs.rs#L115)
- [x] Change runtime boot `struct user_rootfs_config`
- [x] Update `image-rs` and change boot-instance/agent-instance `Dockerfile` to use "upstream" 0.29.6 Occlum

**Comment by haosanzi** [comment]
Hi. Occlum 0.29.5 does Not support runtime boot. The boot-instance occlum should rebase on occlum NGO which support runtime boot.

**Comment by mythi** [comment]
@haosanzi this ticket is to get https://github.com/qzheng527/occlum/tree/enclave-cc rebased to 0.29.5 level and .deb packages made available via http://mirrors.openanolis.cn/inclavare-containers/ubuntu20.04 just like we are doing it today.

**Comment by mythi** [comment]
@haosanzi I think NGO is also OK but I've not seen any activity in the repo since December. What's the NGO status?

**Comment by haosanzi** [comment]
@mythi hi, ngo has changed to Occlum 1.0 has been released but no official release yet. The link: https://github.com/occlum/occlum/tree/1.0.0-preview

**Comment by mythi** [comment]
I re-titled this to cover 0.29.6 update. Details in #112

**Comment by ariel-adam** [comment]
@haosanzi is this on track for 0.7.0 (feature freeze 12th of July) or should we move it to 0.8.0 (it's also in status new on our board: https://github.com/orgs/confidential-containers/projects/6/views/17)?

**Comment by ariel-adam** [comment]
Moving to 0.8.0 given that 0.7.0 feature freeze is happening in 1 week
