### ISSUE TITLE
Add a CI pipeline as close to the Kata Containers one as possible

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/enclave-cc#13]
After chatting with @fidencio about the [confidential-containers first release](https://docs.google.com/presentation/d/1vVN97q3bosJbjyco4dd_25PfnIYNaK3Kg_wCAmvmS4c/edit#slide=id.g132c3a0b3c7_0_5) CI/CD requirements we felt that this would be an essential step for enclave-cc to integrate into the CC release.

### Description

In https://github.com/kata-containers/kata-containers/issues/3992 the Kata containers project is creating a kata-deploy image that can be used in to the operator payload. It also already has some [Kubernetes CC integration tests](https://github.com/kata-containers/tests/tree/CCv0/integration/kubernetes/confidential) as well as a set-up to install the pre-reqs. 

In order to integrate Enclave-CC into the [CC operator](https://github.com/confidential-containers/operator) it needs to build it's own payload image and to demonstrate that Enclave-CC and 'Kata-CC' offer similar levels of functionality the Kata CC tests (or as close as possible) should be run on the Enclave-CC.

**Comment by ariel-adam** [comment]
@stevenhorsman is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by stevenhorsman** [comment]
I believe this is still relevant. It's up to the enclave-cc team as to when they plan to do it, I don't have any input.

**Comment by mythi** [comment]
> I believe this is still relevant. It's up to the enclave-cc team as to when they plan to do it, I don't have any input.

It's relevant and important. I've proposed it to be part of `CC-V0.2.0` Drop.

**Comment by ariel-adam** [comment]
Cool, I've changed the priority to high since you feel it's important :-).

**Comment by hairongchen-intel** [comment]
- [ ] provision a server in public cloud
- [ ] setup Jenkins
- [ ] setup enclave-cc dependencies
- [ ] integrate with github actions
- [ ] setup CI cases

**Comment by hairongchen** [comment]
> @hairongchen-intel what are the "enclave-cc dependencies"?

everything necessary to ensure we can run a component level cases in a host, like the SGX lib, runc/rune, Occlum, containerd/k8s etc.

**Comment by hairongchen** [comment]
operator is one item we definitely should take care of, but we need also let developers have a 'quick' integration path without Kubernets precondition for component test

**Comment by mythi** [comment]
fine but we should not have occlum/rune/sgxsdk pre-installed

**Comment by huliucheng1** [comment]
I'll follow the CI pipeline PR (https://github.com/confidential-containers/operator/pull/133) discussed in the slack channel about monitoring the enclave-cc operator CI state and future extension work.

**Comment by huliucheng1** [comment]
For CI pipeline, a simple flowchart is shown below:

build CI payload image -> run CI test cases -> tag release payload image

Some cases are defined for running CI test:

1. [runtime] Install enclave-cc runtime
2. [feature][positive example] Pull an unencrypted signed image (eaa + verdictd + cosign)
3. [feature][positive example] Pull an encrypted unsigned image (eaa + verdictd)
4. [feature][positive example] Pull an encrypted signed image (eaa + verdictd + cosign)
5. [feature][negative example] Unencrypted signed image with unknown signature is rejected
6. [feature][negative example] Encrypted unsigned image with wrong key is rejected
7. [workload] Deploy a hello-world workload with encrypted signed image
8. [workload] Remove hello-world workload
9. [runtime] Uninstall enclave-cc runtime

**Comment by mythi** [comment]
> Some cases are defined for running CI test:

@huliucheng1 thanks, I think this is a good set of cases. do you have any plans where to maintain/publish these test images (e.g., are they being built before the tests or are they something we get to share with Kata-CI)?

**Comment by hairongchen** [comment]
making sure using same set of testing images and testing artifacts(policy files, keys, etc..) with kata-cc CI according to https://github.com/kata-containers/tests/tree/CCv0/integration/containerd/confidential/fixtures , Thanks @fidencio for the info

**Comment by mythi** [comment]
> In order to integrate Enclave-CC into the [CC operator](https://github.com/confidential-containers/operator) it needs to build it's own payload image and to demonstrate that Enclave-CC and 'Kata-CC' offer similar levels of functionality the Kata CC tests (or as close as possible) should be run on the Enclave-CC.

Some of the steps have been implemented earlier and after #123 I believe we can meet the original request.

- enclave-cc payloads are published automatically, and tested by operator CI for each PR and in nightly builds. the tests setup a `kind` cluster and deploys "simulated" enclave-cc on Github runners
- enclave-cc repository builds payloads for both SIM and HW SGX modes, HW mode is tested on an SGX VM w/ eaa_kbc image decryption and cosign based signature verification
