### ISSUE TITLE
create rootfs_key dynamically and seal it

### ISSUE THREAD

**Issue by mythi** [confidential-containers/enclave-cc#149]
We have been waiting for #20 but in the mean time, let's work on something simpler to get rid of the static `rootfs_key`.

The proposal is to create `rootfs_key` dynamically and seal with with MRSIGNER key from Occlum's getkey `ioctl()`.

Steps:

- [x] #126 
- [x] #114
- [ ] update image-rs Occlum snapshotter to make the key available under the `containerd_id` path
- [ ] update runtime boot to get the key from `containerd_id` path

**Comment by Xynnn007** [comment]
Let me try to understand this:

1. Enclave-agent generates a key randomly, seal the key and then put the encrypted key to `/run/enclave-cc/<containerd_id>`
2. runtime boot get the key from `/run/enclave-cc/<containerd_id>` and unseal it

This implies that the enclave-agent and runtime boot are signed by the same signer, right?

**Comment by mythi** [comment]
@Xynnn007 yes your summary is correct

**Comment by ariel-adam** [comment]
@mythi will this converge for release 0.7.0 (feature freeze 12th of July) or should we move this to 0.8.0?
