### ISSUE TITLE
Get rid of eaa-kbc & verdictd

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/enclave-cc#160]
Now we already have supported cc-kbc with occlum attester.
Gramine is underdevelopment https://github.com/confidential-containers/attestation-agent/pull/212

It is time to get rid of eaa-kbc & verdictd as they are not covered by any CI test now.

**Comment by Xynnn007** [comment]
Oh, it has been done in https://github.com/confidential-containers/enclave-cc/pull/165/files . Let me close this

**Comment by mythi** [comment]
My preference is we drop `KBC=eaa_kbc` completely since we are not validating it and I was thinking this issue covers all the work. I'm OK to submit a new issue about it too

**Comment by Xynnn007** [comment]
Sounds reasonable to me. Let me reopen this issue and assign this to me.
