### ISSUE TITLE
Update Quickstart for v0.8

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/enclave-cc#181]
https://github.com/confidential-containers/community/blob/main/guides/enclave-cc.md 
Mentions verdictd. Should we update this to say cc-kbc?

Also maybe just point them to one of our test files?
https://github.com/confidential-containers/enclave-cc/blob/main/test/e2e/decrypt_config-HW-cc-kbc.conf

We had some feedback that it wasn't clear what to use for IP and Port, for example. So just pointing people to something that will work might be best for the quickstart.

**Comment by Xynnn007** [comment]
cc @houhuiting
