### ISSUE TITLE
update crate with official image-rs 

### ISSUE THREAD

**Issue by zhiwei-intel-h** [confidential-containers/enclave-cc#19]
Will update crate with official image-rs once the https://github.com/confidential-containers/image-rs/pull/37 merged.
`image-rs = { git = "https://github.com/zhiwei-intel-h/image-rs", branch = "dev-occlum-adaption", features = ["occlum_feature"], default-features = false }`

**Comment by YangLiang3** [comment]
https://github.com/confidential-containers/enclave-cc/blob/b6d4d6cd59384a75f11f862fe5f6152b4b3c34de/src/enclave-agent/Cargo.toml#L23
