### ISSUE TITLE
import shim-rune with a clean base from IC project

### ISSUE THREAD

**Issue by jiazhang0** [confidential-containers/enclave-cc#4]

**Comment by haosanzi** [comment]
Current Status：
1. shim-rune rebase on containerd cc-main branch. 
2. Remove unrelated functions in the shim, such as epm, image signature, etc.
3. In the shim create and start APIs, add the function of distinguishing pod_sandbox and pod_container according to the configuration file, and use `rune` to start the `oci bundle` (a demo of occlum-hello) successfully when starting pod_sandbox. However, some functions still need to continue to improve, such as exec and log support etc.
4. After adding cri_handle=cc in the configuration file of containerd, the pull image request of `cri` will call the to pull image of shim-rune, then call the pull image function of enclave-agent container. Right now, enclave-agent is not ready. After the enclave agent is ready, we will debug the `pull image` function between shim-rune and enclave-agent.

**Comment by haosanzi** [comment]
The patches about shim-rune have been committed to inclavare containers repo with [pr](https://github.com/inclavare-containers/inclavare-containers/pull/1572).  After the internal preliminary review and debugging with the agent enclave based on Occlum NGO about unix socket communication, these patches will be pushed to the enclave-cc repo

**Comment by haosanzi** [comment]
Adding unit tests for shim-rune

**Comment by YangLiang3** [comment]
https://github.com/confidential-containers/enclave-cc/pull/17  has been merged
