### ISSUE TITLE
 Invalid SGX device. Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards

### ISSUE THREAD

**Issue by hallowsman** [confidential-containers/enclave-cc#462]
### Describe the bug

1 在模拟环境执行Occlum中的demos里的pytorch时，
按照文档步骤https://github.com/occlum/occlum/tree/master/demos/pytorch/distributed，执行到step4时
cd /root/demos/pytorch/distributed/occlum_instance
WORLD_SIZE=2 RANK=0 OMP_NUM_THREADS=16 occlum run /bin/python3 mnist.py --epoch 3 --no-cuda --seed 42 --save-model
报错如下：
[ERROR] occlum-pal: Failed to create enclave with error code 0x2006: Invalid SGX device. Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards. (line 152, file src/pal_enclave.c)

### How to reproduce

1  With privileged mode特权模式创建容器
`docker run -it --privileged -v /dev/sgx:/dev/sgx occlum/occlum:latest-ubuntu20.04`
`cd /opt/intel/sgxsdk/SampleCode/SampleEnclave`

#### 在Makefile中35行
`SGX_MODE ?= SIM`

`make && ./app`
可以正常执行

2 按照文档编译pytorch https://github.com/occlum/occlum/tree/master/demos/pytorch/distributed ，执行到step时报错

### CoCo version information

occlum

### What TEE are you seeing the problem on

Sgx

**Comment by mythi** [comment]
There's no enclave-cc specifics here so I'm suggesting to report this in the Occlum repo.

**Comment by hallowsman** [comment]
> There's no enclave-cc specifics here so I'm suggesting to report this in the Occlum repo.

then what can i do to solve the problem?

**Comment by mythi** [comment]
The error message tells a lot already but I don't know what expectations the `occlum/occlum:latest-ubuntu20.04` image has on what the device nodes need to be. Therefore my suggestion is to report this elsewhere. We only support `/dev/sgx_*`  on the host and through the SGX SDK libs we install.
