### ISSUE TITLE
enclave-agent build error.

### ISSUE THREAD

**Issue by jiere** [confidential-containers/enclave-cc#72]
Run "make" under src/enclave-agent, met below errors:

error[E0425]: cannot find function `decode_config` in crate `base64`
   --> /home/jie/.cargo/registry/src/github.com-1ecc6299db9ec823/sequoia-openpgp-1.11.0/src/armor/base64_utils.rs:166:19
    |
166 |     match base64::decode_config(&bytes, base64::STANDARD) {
    |                   ^^^^^^^^^^^^^ not found in `base64`

error[E0425]: cannot find value `STANDARD` in crate `base64`
   --> /home/jie/.cargo/registry/src/github.com-1ecc6299db9ec823/sequoia-openpgp-1.11.0/src/armor/base64_utils.rs:166:49
    |
166 |     match base64::decode_config(&bytes, base64::STANDARD) {
    |                                                 ^^^^^^^^ not found in `base64`
    |
help: consider importing this constant
    |
1   | use base64::alphabet::STANDARD;
    |
help: if you import `STANDARD`, refer to it directly
    |
166 -     match base64::decode_config(&bytes, base64::STANDARD) {
166 +     match base64::decode_config(&bytes, STANDARD) {
    |

**Comment by hairongchen** [comment]
this crate is used in image-rs 
@Xynnn007 @arronwy

**Comment by hairongchen** [comment]
base info:
hrc@cre-M50CYP2SBSTD:/tmp/image-rs$  cargo tree |grep  sequoia-openpgp
├── sequoia-openpgp v1.11.0


hrc@cre-M50CYP2SBSTD:/tmp/image-rs$ cargo tree |grep base6
│   ├── base64 v0.13.1
│   │   │   │       └── base64ct v1.5.3
│   │   │   │   │   ├── base64ct v1.5.3
├── base64 v0.13.1
│   │   ├── base64 v0.13.1
│   │   ├── base64 v0.13.1
│   ├── base64 v0.13.1
│   ├── base64-serde v0.6.1
│   │   ├── base64 v0.13.1
│   │   ├── base64 v0.13.1
│       ├── base64 v0.13.1
│   ├── base64 v0.20.0
│   │   │   ├── base64 v0.13.1
│   ├── base64 v0.13.1
│   │   ├── base64 v0.13.1
│   │   │   ├── base64 v0.13.1
│   │   └── base64 v0.13.1
│   │   ├── base64 v0.13.1
│   │   │   ├── base64 v0.13.1
│       ├── base64 v0.13.1
│   ├── base64 v0.13.1

**Comment by Xynnn007** [comment]
Yea, the problems here is very funny. It seems that the definition of `base64` dependency of `sequoia-openpgp` causes this.

* `base64` crate abondoned `decode_config_slice` and some other apis (or change the directory) from ver `0.13.0` to ver `0.20.0`.
* `sequoia-openpgp` asks for a `base64` version `>= 0.12` [here](https://gitlab.com/sequoia-pgp/sequoia/-/blob/main/autocrypt/Cargo.toml#L26) but use `base64`'s `<=0.13.0` apis.
* When image-rs is being built, a `base64 0.20.0` and `sequoia-openpgp 1.11.0` who leverages `base64`'s `0.13.0` api 

The core problem is that `base64` crate was published (1 day ago) with API changed but without modification of major version number.

* A temporary way is to fix `base64` version in image-rs
* A better but future way is wait `base64` crate to be fixed

**Comment by jiere** [comment]
> * A better but future way is wait `sequoia-openpgp` to use a fixed version of `base64`

Thanks so much for your quick finding, @Xynnn007. 
sequoia-openpgp seems to be a Gitlab project, who has account could help raise an issue there?
Anyway, for us, I think the first way makes sense.

**Comment by Xynnn007** [comment]
> sequoia-openpgp seems to be a Gitlab project, who has account could help raise an issue there?

Yea, I'd like to open an issue there. Before this, I found it a little problematic to fix this in image-rs. I will open an PR in enclave-cc to fix this first.

**Comment by Xynnn007** [comment]
FYI, https://gitlab.com/sequoia-pgp/sequoia/-/issues/961 now is fixed. We can update `Cargo.lock` when it is needed.
