### ISSUE TITLE
agent fail to start with "Failed to open Intel SGX device"

### ISSUE THREAD

**Issue by hairongchen** [confidential-containers/enclave-cc#84]
when start container with runc in bundle dir see following error:

root@iZ2ze49w79e4zvkn2mcbscZ:/opt/confidential-containers/share/enclave-cc-agent-instance# runc run 1234567
[get_driver_type /home/sgx/jenkins/ubuntuServer2004-release-build-trunk-218/build_target/PROD/label/Builder-UbuntuSrv20/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
[ERROR] occlum-pal: Failed to create enclave with error code 0x2006: Invalid SGX device. Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards. (line 152, file src/pal_enclave.c)

and the device section in config.json of agent bundle is as below:
    "devices": [
      {
        "path": "/dev/sgx_enclave",
        "type": "c",
        "major": 10,
        "minor": 125,
        "fileMode": 438
      }
    ]

**Comment by mythi** [comment]
check what is the `minor` for that device on your node from `/proc/misc`

**Comment by mythi** [comment]
since we install the SGX SDK libs from their APT repository, we automatically get the latest version 2.18 which is broken due to https://github.com/intel/linux-sgx/issues/920. Creating a symlink from the non-standard `/dev/sgx/enclave -> /dev/sgx_enclave` fixes the problem

**Comment by hairongchen** [comment]
currently our e2e does not check with HW mode so this issue is not reflected in time in all the PR e2e test, this situation should be improved.

**Comment by mythi** [comment]
The SDK fix is expected to be released maybe this week still.

**Comment by hairongchen** [comment]
app container also has this issue:

root@iZ2ze49w79e4zvkn2mcbscZ:~# cat  /var/log/pods/default_enclave-cc-pod_28c552b5-cc3f-4cf4-ab49-c958edd2416b/hello-world/0.log
2023-01-12T00:37:34.512107365+08:00 stderr F [get_driver_type /home/sgx/jenkins/ubuntuServer2004-release-build-trunk-218/build_target/PROD/label/Builder-UbuntuSrv20/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
2023-01-12T00:37:34.512127777+08:00 stderr F [ERROR] occlum-pal: Failed to create enclave with error code 0x2006: Invalid SGX device. Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards. (line 152, file src/pal_enclave.c)

@mythi @haosanzi

**Comment by hairongchen** [comment]
that means to workaround this bug, we need change both agent's config.json  and app's yaml  to add sgx devices:
for this workload POD definition hello_world-enc.yaml
apiVersion: v1
kind: Pod
metadata:
  name: enclave-cc-pod
spec:
  containers:
  - image: docker.io/eqmcc/helloworld_enc
    name: hello-world
    workingDir: "/run/rune/boot_instance/"
    **volumeMounts:
    - mountPath: /dev/sgx/enclave
      name: sgx-enclave
    - mountPath: /dev/sgx/provision
      name: sgx-provision
    securityContext:
      privileged: true**
    resources:
      limits:
        sgx.intel.com/epc: 600Mi
    env:
    - name: OCCLUM_RELEASE_ENCLAVE
      value: "1"
    command:
    - /run/rune/boot_instance/build/bin/occlum-run
    - /bin/hello_world
  runtimeClassName: enclave-cc
  **volumes:
  - name: sgx-enclave
    hostPath:
      path: /dev/sgx_enclave
  - name: sgx-provision
    hostPath:
      path: /dev/sgx_provision**

**Comment by mythi** [comment]
@hairongchen if you create these `/dev/sgx/enclave -> /dev/sgx_enclave` symlinks on the host and use v0.24 device plugin it will just work

**Comment by haosanzi** [comment]
@mythi hi,mikko.

I want to provide more information about this issue. 

Our CI/CD SGX machine the sgx device has the symlinks, and met the `agent fail to start with "Failed to open Intel SGX device" `
```ls -l /dev/sgx/enclave
lrwxrwxrwx 1 root root 14 Jan  9 11:05 /dev/sgx/enclave -> ../sgx_enclave
root@iZ2ze49w79e4zvkn2mcbscZ:~# ls -l /dev/sgx/provision
lrwxrwxrwx 1 root root 16 Jan  9 11:05 /dev/sgx/provision -> ../sgx_provision
```

The fix solution is to mount host `/dev/sgx_enclave` to `/dev/sgx/enclave` in the container environment. 

The Root cause is:  after analysis the SDK code, we found that SGX SDK does not provide the support `/dev/sgx_enclave`. 
Therefore, if we have `/dev/sgx_enclave` in the container environment, we will meet the `Failed to open Intel SGX device.` problem. We need to have `/dev/sgx/enclave` in container environment,.

```sh
// @psw/urts/linux/edmm_utility.cpp
int hdev = open("/dev/sgx/enclave", O_RDWR);    //attempt to open the in-kernel driver
if (-1 == hdev)
{
    hdev = open("/dev/isgx", O_RDWR);    //attempt to open the out-of-tree driver
    if (-1 == hdev)
    {
        hdev = open("/dev/sgx", O_RDWR);  //attempt to open the DCAP driver
        if (-1 == hdev)
        {
            SE_PROD_LOG("Failed to open Intel SGX device.\n");
            return false;
        }
        sgx_driver_type = SGX_DRIVER_DCAP;
    }
    else
    {
        sgx_driver_type = SGX_DRIVER_OUT_OF_TREE;
    }
}
else
{
    sgx_driver_type = SGX_DRIVER_IN_KERNEL;
}
```

Based on the above analysis, I think `use v0.24 device plugin it will just work` may not work because [it seems mount to `/dev/sgx_enclave`in container environment](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/v0.24.0/deployments/sgx_plugin/base/intel-sgx-plugin.yaml#L32).  Please correct me if I am wrong. Thank you.

**Comment by hairongchen** [comment]
> @hairongchen if you create these `/dev/sgx/enclave -> /dev/sgx_enclave` symlinks on the host and use v0.24 device plugin it will just work

that's sth we can keep investigating after the release, now the CI machine as the link already andrunning v0.25 plugin, but not work. 
But I don't suggest do the changes for plugin version for now since we already spent time to find workaround for now, this will keep CI base env stable.

**Comment by hairongchen** [comment]
PR for temp fix: https://github.com/confidential-containers/enclave-cc/pull/90

**Comment by haosanzi** [comment]
> @hairongchen if you create these `/dev/sgx/enclave -> /dev/sgx_enclave` symlinks on the host and use v0.24 device plugin it will just work

Make sense. Since [0.24.0 intel sgx plugin](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/v0.24.0/deployments/sgx_plugin/base/intel-sgx-plugin.yaml#L29) mount `/dev/sgx` dir to `/dev/sgx` dir in container environment. Thank you very much.

**Comment by hairongchen** [comment]
> 

this would work for workload container, but agent still need these devices to be mounted in as it does not as k8s to add sgx resource via plugin.

**Comment by mythi** [comment]
>  agent still need these devices to be mounted 

`/dev/sgx` dir volume mount alone is enough.
